### ISSUE TITLE
CM error: Portable CM script failed (name = process-mlperf-accuracy, return code = 1)

### ISSUE THREAD

**Issue by RommelCF** [mlcommons/cm4mlops#112]
I'm attempting to run RetinaNet from the MLperf, SingleStream but other presets fail as well on an AMD CPU under windows11, using the following cmds:

```
cm run script --tags=run-mlperf,inference,_r4.1 \
   --model=retinanet \
   --implementation=reference \
   --framework=onnxruntime \
   --category=edge \
   --scenario=SingleStream \
   --execution_mode=valid \
   --device=cpu \
   --quiet

```

```
Traceback (most recent call last):
  File "C:\Users\Administrator\CM\repos\local\cache\659b01c191264133\inference\vision\classification_and_detection\tools\accuracy-openimages.py", line 119, in <module>
    main()
  File "C:\Users\Administrator\CM\repos\local\cache\659b01c191264133\inference\vision\classification_and_detection\tools\accuracy-openimages.py", line 39, in main
    cocoGt = COCO(annotations_file, use_ext=True)
TypeError: COCO.__init__() got an unexpected keyword argument 'use_ext'

CM error: Portable CM script failed (name = process-mlperf-accuracy, return code = 1)
```
Attached is the output from adding the --repro flag.
[cm-run-script-input.json](https://github.com/user-attachments/files/16235930/cm-run-script-input.json)

**Comment by arjunsuresh** [comment]
Can you please do
`cm pull repo` and retry the command? `nvidia-pycocotools` had an issue building on macOS and is disabled now.

**Comment by RommelCF** [comment]
I could not find `nvidia-pycocotools,` but just `cm pull repo` and `pycocotools` did the trick.

**Comment by RommelCF** [comment]
Closing it since that fixed it.
