### ISSUE TITLE
Getting SyntaxError: invalid syntax when running mlperf,inference 

### ISSUE THREAD

**Issue by NugentCJ** [mlcommons/cm4mlops#147]
cm run script --tags=run-mlperf,inference,_performance-only,_short     
                        --division=open    
                        --category=network    
                        --device=cuda    
                        --model=resnet50    
                        --precision=float32    
                        --implementation=nvidia    
                        --backend=tensorrt    
                        --scenario=Offline    
                        --execution_mode=test    -
                        -power=no    
                        --adr.python.version_min=3.8    
                        --clean    
                        --compliance=no    
                        --quiet   
                         --time   
                         --docker

Then return with following error:

INFO:root:           ! call /home/cmuser/CM/repos/gateoverflow@cm4mlops/script/app-mlperf-inference-nvidia/run.sh from tmp-run.sh
make generate_engines RUN_ARGS=' --benchmarks=resnet50 --scenarios=offline  --test_mode=PerformanceOnly  --gpu_batch_size=2048 --no_audit_verify  '
[2024-07-30 11:50:50,953 main.py:229 INFO] Detected system ID: KnownSystem.H100_SXM_80GBx8
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cmuser/CM/repos/local/cache/7f21f329fbc04683/repo/closed/NVIDIA/code/main.py", line 231, in <module>
    main(main_args, DETECTED_SYSTEM)
  File "/home/cmuser/CM/repos/local/cache/7f21f329fbc04683/repo/closed/NVIDIA/code/main.py", line 103, in main
    load_config_fn(benchmarks, scenarios)
  File "/home/cmuser/CM/repos/local/cache/7f21f329fbc04683/repo/closed/NVIDIA/code/main.py", line 53, in populate_config_registry
    ConfigRegistry.load_configs(benchmark, scenario)
  File "/home/cmuser/CM/repos/local/cache/7f21f329fbc04683/repo/closed/NVIDIA/configs/configuration.py", line 123, in load_configs
    importlib.import_module(f"{base_module}.custom")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cmuser/CM/repos/local/cache/7f21f329fbc04683/repo/closed/NVIDIA/configs/resnet50/Offline/custom.py", line 8
    class DGX-H100_H100-SXM-80GBX8(OfflineGPUBaseConfig):
             ^
SyntaxError: invalid syntax
make: *** [Makefile:37: generate_engines] Error 1

CM error: Portable CM script failed (name = app-mlperf-inference-nvidia, return code = 256)

Error seems to be the class name is invalid as it contains a hyphen, but not sure how that is getting set.

**Comment by arjunsuresh** [comment]
Closing this issue. Feel free to reopen if issue persists.
