### ISSUE TITLE
Check, fix and document the usage of --const

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/cm4mlops#225]
`--const` is seldom used in the CM workflows. Its usage needs to be tested and documented.

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , just checked adding it to end of a cm run command:
```
cm run script "get dataset imagenet image-classification original _run-during-docker-build" --const
```

got an error:

```
anandhu@intel-spr-i9:~$ cm run script "get dataset imagenet image-classification original _run-during-docker-build" --const
INFO:root:* cm run script "get dataset imagenet image-classification original _run-during-docker-build"
INFO:root:  * cm run script "detect os"
Traceback (most recent call last):
  File "/home/anandhu/.local/bin/cm", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/anandhu/.local/lib/python3.12/site-packages/cmind/cli.py", line 37, in run
    r = cm.access(argv, out='con')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anandhu/.local/lib/python3.12/site-packages/cmind/core.py", line 602, in access
    r = action_addr(i)
        ^^^^^^^^^^^^^^
  File "/home/anandhu/CM/repos/anandhu-eng@cm4mlops/automation/script/module.py", line 212, in run
    r = self._run(i)
        ^^^^^^^^^^^^
  File "/home/anandhu/CM/repos/anandhu-eng@cm4mlops/automation/script/module.py", line 1367, in _run
    r = self._call_run_deps(deps, self.local_env_keys, local_env_keys_from_meta, env, state, const, const_state, add_deps_recursive,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anandhu/CM/repos/anandhu-eng@cm4mlops/automation/script/module.py", line 2882, in _call_run_deps
    r = script._run_deps(deps, local_env_keys, env, state, const, const_state, add_deps_recursive, recursion_spaces,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anandhu/CM/repos/anandhu-eng@cm4mlops/automation/script/module.py", line 3033, in _run_deps
    r = self.cmind.access(ii)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anandhu/.local/lib/python3.12/site-packages/cmind/core.py", line 602, in access
    r = action_addr(i)
        ^^^^^^^^^^^^^^
  File "/home/anandhu/CM/repos/anandhu-eng@cm4mlops/automation/script/module.py", line 212, in run
    r = self._run(i)
        ^^^^^^^^^^^^
  File "/home/anandhu/CM/repos/anandhu-eng@cm4mlops/automation/script/module.py", line 1466, in _run
    utils.merge_dicts({'dict1':env, 'dict2':const, 'append_lists':True, 'append_unique':True})
  File "/home/anandhu/.local/lib/python3.12/site-packages/cmind/utils.py", line 852, in merge_dicts
    for k in b:
TypeError: 'bool' object is not iterable
```

**Comment by gfursin** [comment]
I implemented --const to force the value of specific environment variables in all sub-scripts even if they are dynamically changing. 

It has the following format:
```
--const.key=value
```

You can't use --const as it is since it will be converted to bool and will result in above error ...

I don't think we use it a lot nowadays but it may still be useful - I suggest to keep it as some of my past CM scripts and workflows can depend on it ...

**Comment by arjunsuresh** [comment]
`const` implementation is now made proper and test case added.
