### ISSUE TITLE
Key Error when running script `get-dataset-coco`

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#281]
To reproduce:
```
cm run script --tags=get,dataset,object-detection,coco
```

Error:
```
extracting: val2017/000000523957.jpg
 extracting: val2017/000000570539.jpg
 extracting: val2017/000000470121.jpg
 extracting: val2017/000000199442.jpg
 extracting: val2017/000000563653.jpg
 extracting: val2017/000000181421.jpg
 extracting: val2017/000000302990.jpg
 extracting: val2017/000000446005.jpg
 extracting: val2017/000000329219.jpg
 extracting: val2017/000000388258.jpg
 extracting: val2017/000000126137.jpg
 extracting: val2017/000000500826.jpg


INFO:root:         ! call "postprocess" from /root/CM/repos/gateoverflow@cm4mlops/script/extract-file/customize.py
INFO:root:  * cm run script "download-and-extract file _wget _extract _url.http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
INFO:root:    * cm run script "download file _wget _url.http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
INFO:root:      * cm run script "detect os"
INFO:root:             ! cd /root/CM/repos/local/cache/e954e9d2ead24b5d
INFO:root:             ! call /root/CM/repos/gateoverflow@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:             ! call "postprocess" from /root/CM/repos/gateoverflow@cm4mlops/script/detect-os/customize.py

Downloading from http://images.cocodataset.org/annotations/annotations_trainval2017.zip
Traceback (most recent call last):
  File "/usr/local/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/cmind/cli.py", line 37, in run
    r = cm.access(argv, out='con')
  File "/usr/local/lib/python3.10/dist-packages/cmind/core.py", line 605, in access
    r = action_addr(i)
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 212, in run
    r = self._run(i)
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 1537, in _run
    r = self._call_run_deps(prehook_deps, self.local_env_keys, local_env_keys_from_meta,  env, state, const, const_state, add_deps_recursive,
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 2882, in _call_run_deps
    r = script._run_deps(deps, local_env_keys, env, state, const, const_state, add_deps_recursive, recursion_spaces,
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 3033, in _run_deps
    r = self.cmind.access(ii)
  File "/usr/local/lib/python3.10/dist-packages/cmind/core.py", line 605, in access
    r = action_addr(i)
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 212, in run
    r = self._run(i)
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 1537, in _run
    r = self._call_run_deps(prehook_deps, self.local_env_keys, local_env_keys_from_meta,  env, state, const, const_state, add_deps_recursive,
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 2882, in _call_run_deps
    r = script._run_deps(deps, local_env_keys, env, state, const, const_state, add_deps_recursive, recursion_spaces,
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 3033, in _run_deps
    r = self.cmind.access(ii)
  File "/usr/local/lib/python3.10/dist-packages/cmind/core.py", line 605, in access
    r = action_addr(i)
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 212, in run
    r = self._run(i)
  File "/root/CM/repos/gateoverflow@cm4mlops/automation/script/module.py", line 1477, in _run
    r = customize_code.preprocess(ii)
  File "/root/CM/repos/gateoverflow@cm4mlops/script/download-file/customize.py", line 72, in preprocess
    os.chdir(download_path)
NotADirectoryError: [Errno 20] Not a directory: '/root/CM/repos/local/cache/ef2a63d477a2419a/val2017.zip'
```

**Comment by arjunsuresh** [comment]
Fixed now.
