### ISSUE TITLE
KeyError while SDXL reference implementation run for lesser input size than original

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#286]
to reproduce:
```
cm run script --tags=run-mlperf,inference,_r4.1-dev,_short,_scc24-base    --model=sdxl    --implementation=reference    --framework=pytorch    --category=edge    --scenario=Offline    --execution_mode=test    --device=cuda    --quiet --rerun
```

error:
```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.46it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.46it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.46it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.46it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.46it/s]
INFO:root:Loading pretrained ViT-B-32 from OpenAI.
INFO:coco:Accumulating results

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 391, in get_loc
    return self._range.index(new_key)
ValueError: 4655 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference/text_to_image/main.py", line 500, in <module>
    main()
  File "/home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference/text_to_image/main.py", line 485, in main
    post_proc.save_images(saved_images_ids, ds)
  File "/home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference/text_to_image/coco.py", line 175, in save_images
    caption = ds.get_caption(id)
  File "/home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference/text_to_image/coco.py", line 129, in get_caption
    return self.get_item(i)["caption"]
  File "/home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference/text_to_image/coco.py", line 113, in get_item
    return dict(self.captions_df.loc[id], latents=self.latents)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1312, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1260, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 4056, in xs
    loc = index.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 393, in get_loc
    raise KeyError(key) from err
KeyError: 4655
INFO:root:         ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/benchmark-program/customize.py
INFO:root:  * cm run script "save mlperf inference state"
INFO:root:         ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/save-mlperf-inference-implementation-state/customize.py
INFO:root:       ! cd /home/cmuser
INFO:root:       ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/app-mlperf-inference/run.sh from tmp-run.sh
INFO:root:       ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/app-mlperf-inference/customize.py
INFO:root:* cm run script "get mlperf sut description"
INFO:root:  * cm run script "detect os"
INFO:root:         ! cd /home/cmuser
INFO:root:         ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:         ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/customize.py
INFO:root:  * cm run script "detect cpu"
INFO:root:    * cm run script "detect os"
INFO:root:           ! cd /home/cmuser
INFO:root:           ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:           ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/customize.py
INFO:root:         ! cd /home/cmuser
INFO:root:         ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-cpu/run.sh from tmp-run.sh
INFO:root:         ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-cpu/customize.py
INFO:root:  * cm run script "get python3"
INFO:root:       ! load /home/cmuser/CM/repos/local/cache/d0ffbf4f1fc548c6/cm-cached-state.json
INFO:root:Path to Python: /usr/bin/python3
INFO:root:Python version: 3.10.12
INFO:root:  * cm run script "get compiler"
INFO:root:       ! load /home/cmuser/CM/repos/local/cache/d38c76e821614415/cm-cached-state.json
INFO:root:  * cm run script "get cuda-devices"
INFO:root:    * cm run script "get cuda _toolkit"
INFO:root:         ! load /home/cmuser/CM/repos/local/cache/9ef782b570874755/cm-cached-state.json
INFO:root:ENV[CM_CUDA_PATH_LIB_CUDNN_EXISTS]: no
INFO:root:ENV[CM_CUDA_VERSION]: 12.4
INFO:root:ENV[CM_CUDA_VERSION_STRING]: cu124
INFO:root:ENV[CM_NVCC_BIN_WITH_PATH]: /usr/local/cuda/bin/nvcc
INFO:root:ENV[CUDA_HOME]: /usr/local/cuda
INFO:root:         ! cd /home/cmuser
INFO:root:         ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-cuda-devices/run.sh from tmp-run.sh
rm: cannot remove 'a.out': No such file or directory

NVCC path: /usr/local/cuda/bin/nvcc


Checking compiler version ...

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

Compiling program ...


Running program ...

/home/cmuser
INFO:root:         ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-cuda-devices/customize.py
GPU Device ID: 0
GPU Name: NVIDIA GeForce RTX 4090
GPU compute capability: 8.9
CUDA driver version: 12.2
CUDA runtime version: 12.4
Global memory: 25393692672
Max clock rate: 2520.000000 MHz
Total amount of shared memory per block: 49152
Total number of registers available per block: 65536
Warp size: 32
Maximum number of threads per multiprocessor:  1536
Maximum number of threads per block: 1024
Max dimension size of a thread block X: 1024
Max dimension size of a thread block Y: 1024
Max dimension size of a thread block Z: 64
Max dimension size of a grid size X: 2147483647
Max dimension size of a grid size Y: 65535
Max dimension size of a grid size Z: 65535


INFO:root:  * cm run script "get generic-python-lib _package.dmiparser"
INFO:root:       ! load /home/cmuser/CM/repos/local/cache/e1ef549d69404e11/cm-cached-state.json
INFO:root:  * cm run script "get cache dir _name.mlperf-inference-sut-descriptions"
INFO:root:       ! load /home/cmuser/CM/repos/local/cache/50c54ad88fbc4498/cm-cached-state.json
Generating SUT description file for edfeba9b2e42-pytorch-2.3.0a0
INFO:root:       ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-mlperf-inference-sut-description/customize.py
INFO:root:* cm run script "run accuracy mlperf _coco2014"
INFO:root:  * cm run script "get python3"
INFO:root:       ! load /home/cmuser/CM/repos/local/cache/d0ffbf4f1fc548c6/cm-cached-state.json
INFO:root:Path to Python: /usr/bin/python3
INFO:root:Python version: 3.10.12
INFO:root:  * cm run script "get mlcommons inference src"
INFO:root:       ! load /home/cmuser/CM/repos/local/cache/2296afc42a314891/cm-cached-state.json
INFO:root:  * cm run script "get dataset coco2014 original"
INFO:root:       ! load /home/cmuser/CM/repos/local/cache/e2bffd2c27e44004/cm-cached-state.json
INFO:root:  * cm run script "get generic-python-lib _package.ijson"
INFO:root:       ! load /home/cmuser/CM/repos/local/cache/070f57d2f9714542/cm-cached-state.json
INFO:root:       ! cd /home/cmuser
INFO:root:       ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/process-mlperf-accuracy/run.sh from tmp-run.sh
/usr/bin/python3 '/home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference/text_to_image/tools/accuracy_coco.py' --mlperf-accuracy-file '/home/cmuser/CM/repos/local/cache/c8d076bc3bbc4225/test_results/edfeba9b2e42-reference-gpu-pytorch-v2.3.0a0-default_config/stable-diffusion-xl/offline/accuracy/mlperf_log_accuracy.json' --caption-path '/home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference/text_to_image/coco2014/captions/captions_source.tsv' --compliance-images-path /home/cmuser/CM/repos/local/cache/c8d076bc3bbc4225/test_results/edfeba9b2e42-reference-gpu-pytorch-v2.3.0a0-default_config/stable-diffusion-xl/offline/accuracy/images  > '/home/cmuser/CM/repos/local/cache/c8d076bc3bbc4225/test_results/edfeba9b2e42-reference-gpu-pytorch-v2.3.0a0-default_config/stable-diffusion-xl/offline/accuracy/accuracy.txt'
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 22.99it/s]
INFO:root:       ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/process-mlperf-accuracy/customize.py

Accuracy file: /home/cmuser/CM/repos/local/cache/c8d076bc3bbc4225/test_results/edfeba9b2e42-reference-gpu-pytorch-v2.3.0a0-default_config/stable-diffusion-xl/offline/accuracy/accuracy.txt

Accuracy Results: {'FID_SCORE': 237.19364203621626, 'CLIP_SCORE': 15.183445751667023}


Running:
/usr/bin/python3 /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/dump-pip-freeze/dump.py

edfeba9b2e42-reference-gpu-pytorch-v2.3.0a0-default_config
+---------------------+----------+-------------------------+------------+-----------------+
|        Model        | Scenario |        Accuracy         | Throughput | Latency (in ms) |
+---------------------+----------+-------------------------+------------+-----------------+
| stable-diffusion-xl | Offline  | X (15.18345, 237.19364) |   0.161    |        -        |
+---------------------+----------+-------------------------+------------+-----------------+

The MLPerf inference results are stored at /home/cmuser/CM/repos/local/cache/c8d076bc3bbc4225/test_results

INFO:root:       ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/run-mlperf-inference-app/customize.py

Path to the MLPerf inference benchmark reference sources: /home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference
Path to the MLPerf inference reference configuration file: /home/cmuser/CM/repos/local/cache/0c64ea376c2d4d00/inference/mlperf.conf
```

**Comment by arjunsuresh** [comment]
This I'll fix - we need to change the list of image IDs for which outputs are generated.

**Comment by arjunsuresh** [comment]
We have to use the below argument to pass a file containing the first 10 image IDs which will work for both `scc-base` and `scc-main`.

https://github.com/mlcommons/inference/blob/master/text_to_image/main.py#L142
