### ISSUE TITLE
Error parsing message with type 'tensorflow.GraphDef'

### ISSUE THREAD

**Issue by uscinski-cpu** [mlcommons/cm4mlops#425]
I get this error every time I complete a run:

`Instructions for updating:
Use tf.gfile.GFile.
Traceback (most recent call last):
  File "C:\Users\hp\CM\repos\local\cache\3828644e47b24b97\inference\vision\classification_and_detection\python\main.py", line 716, in <module>
    main()
  File "C:\Users\hp\CM\repos\local\cache\3828644e47b24b97\inference\vision\classification_and_detection\python\main.py", line 585, in main
    model = backend.load(
            ^^^^^^^^^^^^^
  File "C:\Users\hp\CM\repos\local\cache\3828644e47b24b97\inference\vision\classification_and_detection\python\backend_tf.py", line 48, in load
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'

CM error: Portable CM script failed (name = benchmark-program, return code = 1)`

**Comment by uscinski-cpu** [comment]
these are packages installed:

absl-py==2.1.0
astunparse==1.6.3
boto3==1.35.49
botocore==1.35.49
certifi==2024.8.30
charset-normalizer==3.4.0
cm==0.1a2
cm4mlops==0.3.23
cmind==3.2.8
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.3.0
cycler==0.12.1
dmiparser==5.1
filelock==3.16.1
flatbuffers==24.3.25
fonttools==4.54.1
fsspec==2024.10.0
gast==0.6.0
giturlparse==0.12.0
google-pasta==0.2.0
grpcio==1.67.0
h5py==3.12.1
humanfriendly==10.0
idna==3.10
Jinja2==3.1.4
jmespath==1.0.1
keras==3.6.0
kiwisolver==1.4.7
libclang==18.1.1
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib==3.9.2
mdurl==0.1.2
ml-dtypes==0.4.1
-e git+https://github.com/mlcommons/inference@f74d16f54131d9080b9e45f234cc23e0ebaaf20c#egg=mlcommons_loadgen&subdirectory=loadgen
mpmath==1.3.0
namex==0.0.8
networkx==3.4.2
numpy==1.26.4
onnxruntime==1.19.2
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
opt_einsum==3.4.0
optree==0.13.0
packaging==24.1
pandas==2.2.3
pillow==11.0.0
protobuf==5.28.3
psutil==6.1.0
pybind11==2.13.6
pycocotools==2.0.8
Pygments==2.18.0
pyparsing==3.2.0
pyreadline3==3.5.4
python-dateutil==2.9.0.post0
pytz==2024.2
PyYAML==6.0.2
requests==2.32.3
rich==13.9.3
s3transfer==0.10.3
setuptools==75.2.0
simplejson==3.19.3
six==1.16.0
sympy==1.13.1
tabulate==0.9.0
tensorboard==2.18.0
tensorboard-data-server==0.7.2
tensorflow==2.18.0
tensorflow_intel==2.18.0
termcolor==2.5.0
torch==2.5.0+cpu
torchvision==0.20.0+cpu
tqdm==4.66.5
typing_extensions==4.12.2
tzdata==2024.2
ujson==5.10.0
urllib3==2.2.3
Werkzeug==3.0.6
wheel==0.44.0
wrapt==1.16.0
