### ISSUE TITLE
"compressed_tensors" module missing - llama2 70 b reference

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#429]
```
/home/cmuser/venv/cm/bin/python3 main.py  --scenario Offline --dataset-path /home/cmuser/CM/repos/local/cache/6a1b601666af4e67/open_orca/open_orca_gpt4_tokenized_llama.sampled_24576.pkl.gz --device cpu   --user-conf '/home/cmuser/CM/repos/mlcommons@cm4mlops/script/generate-mlperf-inference-user-conf/tmp/a3278f7102d94ee08a8df3184434ef78.conf' --output-log-dir /cm-mount/home/anandhu/CM/repos/anandhu-eng@cm4mlops/test_results/7703229195a6-reference-cpu-pytorch-v2.5.0-default_config/llama2-70b-99/offline/performance/run_1 --dtype float32 --model-path /home/cmuser/CM/repos/local/cache/4116af2beb99410c/repo 2>&1 ; echo $? > exitstatus | tee '/cm-mount/home/anandhu/CM/repos/anandhu-eng@cm4mlops/test_results/7703229195a6-reference-cpu-pytorch-v2.5.0-default_config/llama2-70b-99/offline/performance/run_1/console.out'
INFO:datasets:PyTorch version 2.5.0+cpu available.
Loading dataset...
Finished loading dataset.
Traceback (most recent call last):
  File "/home/cmuser/CM/repos/local/cache/3caef9693b8c4891/inference/language/llama2-70b/main.py", line 214, in <module>
    main()
  File "/home/cmuser/CM/repos/local/cache/3caef9693b8c4891/inference/language/llama2-70b/main.py", line 180, in main
    sut = sut_cls(
  File "/home/cmuser/CM/repos/local/cache/3caef9693b8c4891/inference/language/llama2-70b/SUT.py", line 123, in __init__
    self.load_model()
  File "/home/cmuser/CM/repos/local/cache/3caef9693b8c4891/inference/language/llama2-70b/SUT.py", line 231, in load_model
    self.model = LlamaForCausalLM.from_pretrained(
  File "/home/cmuser/venv/cm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3646, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
  File "/home/cmuser/venv/cm/lib/python3.10/site-packages/transformers/quantizers/auto.py", line 173, in merge_quantization_configs
    quantization_config = AutoQuantizationConfig.from_dict(quantization_config)
  File "/home/cmuser/venv/cm/lib/python3.10/site-packages/transformers/quantizers/auto.py", line 103, in from_dict
    return target_cls.from_dict(quantization_config_dict)
  File "/home/cmuser/venv/cm/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 1159, in from_dict
    return super().from_dict(config_dict, return_unused_kwargs=return_unused_kwargs, **kwargs)
  File "/home/cmuser/venv/cm/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 102, in from_dict
    config = cls(**config_dict)
  File "/home/cmuser/venv/cm/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 1107, in __init__
    from compressed_tensors import QuantizationConfig
ModuleNotFoundError: No module named 'compressed_tensors'
```

**Comment by anandhu-eng** [comment]
PR merged
