### ISSUE TITLE
No SUDO access but INFO:root:  * cm run script "detect sudo"

### ISSUE THREAD

**Issue by zixianwang2022** [mlcommons/cm4mlops#510]
Hi, I don't have sudo access, but I was asked to provide sudo password when running the following command: 

```
cm run script --tags=run-mlperf,inference,_r4.1-dev,_short,_scc24-base \
   --model=sdxl \
   --framework=pytorch \
   --category=datacenter \
   --scenario=Offline \
   --execution_mode=test \
   --device=rocm \
   --quiet --precision=float16 
```

```
INFO:root:  * cm run script "detect sudo"

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for ziw081:
```

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022 you can simply wait for 20s and it'll automatically skip the utils which needs sudo. 

@anandhu-eng Is it possible to ask users to press Enter to avoid this waiting?

**Comment by zixianwang2022** [comment]
Hello @arjunsuresh, even if I wait for 20 seconds without entering password, it still says

```
 dnf install -y psmisc
Error: This command has to be run with superuser privileges (under the root user on most systems).
Command failed with status 0
```


Following is a more comprehensive log. 

```
INFO:root:  * cm run script "detect os"
INFO:root:         ! cd /work1/zixian/ziw081/CM/repos/local/cache/9621b755fc62472b
INFO:root:         ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:         ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:  * cm run script "detect sudo"

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for ziw081:Timeout occurred. Do you want to try again? (y/n): 
No input received in 10 seconds. Exiting.
INFO:root:         ! cd /work1/zixian/ziw081/CM/repos/local/cache/9621b755fc62472b
INFO:root:         ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-sudo/run.sh from tmp-run.sh
INFO:root:         ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-sudo/customize.py
INFO:root:  * cm run script "get sys-util generic _psmisc"
INFO:root:    * cm run script "detect os"
INFO:root:           ! cd /work1/zixian/ziw081/CM/repos/local/cache/143bc7ed6d8646af
INFO:root:           ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:           ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:    * cm run script "get generic-sys-util _install _psmisc"
INFO:root:      * cm run script "detect os"
INFO:root:             ! cd /work1/zixian/ziw081/CM/repos/local/cache/8ca7494e1dce4d06
INFO:root:             ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:             ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:           ! cd /work1/zixian/ziw081/CM/repos/local/cache/8ca7494e1dce4d06
INFO:root:           ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/get-generic-sys-util/install.sh from tmp-run.sh
 dnf install -y psmisc
Error: This command has to be run with superuser privileges (under the root user on most systems).
Command failed with status 0

CM error: Portable CM script failed (name = get-generic-sys-util, return code = 256)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note that it is often a portability issue of a third-party tool or a native script
wrapped and unified by this CM script (automation recipe). Please re-run
this script with --repro flag and report this issue with the original
command line, cm-repro directory and full log here:

https://github.com/mlcommons/cm4mlops/issues

The CM concept is to collaboratively fix such issues inside portable CM scripts
to make existing tools and native scripts more portable, interoperable
and deterministic. Thank you!
```

Command to run:
```
cm run script --tags=run-mlperf,inference,_find-performance,_r4.1-dev,_short,_scc24-base    --model=sdxl    --implementation=reference    --framework=pytorch    --category=datacenter    --scenario=Offline    --execution_mode=test    --device=rocm     --quiet     --precision=float16
```

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022 , can you please do `cm pull repo` and retry the command?

**Comment by zixianwang2022** [comment]
Hello @arjunsuresh , 

I tried `cm pull repo` and rerun the script. However, it is still giving me the error. 

```
INFO:root:Python version: 3.10.14
INFO:root:  * cm run script "get compiler"
INFO:root:       ! load /work1/zixian/ziw081/CM/repos/local/cache/3ea44324d2cf4a42/cm-cached-state.json
INFO:root:  * cm run script "get generic-python-lib _package.dmiparser"
INFO:root:       ! load /work1/zixian/ziw081/CM/repos/local/cache/fded4801de8b4bbe/cm-cached-state.json
INFO:root:  * cm run script "get cache dir _name.mlperf-inference-sut-descriptions"
INFO:root:       ! load /work1/zixian/ziw081/CM/repos/local/cache/90c74a04e60b4c0d/cm-cached-state.json
Generating SUT description file for t006_006.hpcfund-pytorch-2.6.0.dev20241108
INFO:root:       ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/get-mlperf-inference-sut-description/customize.py
INFO:root:* cm run script "get platform details"
INFO:root:  * cm run script "detect os"
INFO:root:         ! cd /work1/zixian/ziw081/CM/repos/local/cache/9621b755fc62472b
INFO:root:         ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:         ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:  * cm run script "detect sudo"

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for ziw081:Timeout occurred. Do you want to try again? (y/n): n
INFO:root:         ! cd /work1/zixian/ziw081/CM/repos/local/cache/9621b755fc62472b
INFO:root:         ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-sudo/run.sh from tmp-run.sh
INFO:root:         ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-sudo/customize.py
INFO:root:  * cm run script "get sys-util generic _psmisc"
INFO:root:    * cm run script "detect os"
INFO:root:           ! cd /work1/zixian/ziw081/CM/repos/local/cache/143bc7ed6d8646af
INFO:root:           ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:           ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:    * cm run script "get generic-sys-util _install _psmisc"
INFO:root:      * cm run script "detect os"
INFO:root:             ! cd /work1/zixian/ziw081/CM/repos/local/cache/8ca7494e1dce4d06
INFO:root:             ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:             ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:           ! cd /work1/zixian/ziw081/CM/repos/local/cache/8ca7494e1dce4d06
INFO:root:           ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/get-generic-sys-util/install.sh from tmp-run.sh
 dnf install -y psmisc
Error: This command has to be run with superuser privileges (under the root user on most systems).
Command failed with status 0

CM error: Portable CM script failed (name = get-generic-sys-util, return code = 256)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note that it is often a portability issue of a third-party tool or a native script
wrapped and unified by this CM script (automation recipe). Please re-run
this script with --repro flag and report this issue with the original
command line, cm-repro directory and full log here:

https://github.com/mlcommons/cm4mlops/issues

The CM concept is to collaboratively fix such issues inside portable CM scripts
to make existing tools and native scripts more portable, interoperable
and deterministic. Thank you!
```


Here is my run command
```
cm run script --tags=run-mlperf,inference,_find-performance,_r4.1-dev,_short,_scc24-base    --model=sdxl    --implementation=reference    --framework=pytorch    --category=datacenter    --scenario=Offline    --execution_mode=test    --device=rocm     --quiet     --precision=float16
```

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022 was the `cm pull repo` command successful? If you have done any local changes to the CM repo, you will need to `cd $HOME/CM/repos/mlcommons@cm4mlops && git stash && git pull && git stash apply`.

**Comment by arjunsuresh** [comment]
@anandhu-eng I have added "-1" in `detect-sudo`. Please check it.

**Comment by zixianwang2022** [comment]
Hello @arjunsuresh , I did follow the commands and they did pull successfully. However, I am still getting the error. 

```
(mlperf_1) (base) [ziw081@t006-006 mlcommons@cm4mlops]$ git stash && git pull && git stash apply
Saved working directory and index state WIP on mlperf-inference: da6af8c1d Merge pull request #512 from GATEOverflow/mlperf-inference
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 774 bytes | 86.00 KiB/s, done.
From https://github.com/mlcommons/cm4mlops
   da6af8c1d..159a1fca0  mlperf-inference -> origin/mlperf-inference
Updating da6af8c1d..159a1fca0
Fast-forward
 script/detect-sudo/customize.py | 50 ++++++++++++++++++++++++++++++++------------------
 1 file changed, 32 insertions(+), 18 deletions(-)
On branch mlperf-inference
Your branch is up to date with 'origin/mlperf-inference'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   script/get-rocm/customize.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        hardware/

no changes added to commit (use "git add" and/or "git commit -a")
```



```
INFO:root:* cm run script "get platform details"
INFO:root:  * cm run script "detect os"
INFO:root:         ! cd /work1/zixian/ziw081/CM/repos/local/cache/9621b755fc62472b
INFO:root:         ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:         ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:  * cm run script "detect sudo"
Enter password (-1 to skip): 
Skipping sudo command.
INFO:root:         ! cd /work1/zixian/ziw081/CM/repos/local/cache/9621b755fc62472b
INFO:root:         ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-sudo/run.sh from tmp-run.sh
INFO:root:         ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-sudo/customize.py
INFO:root:  * cm run script "get sys-util generic _psmisc"
INFO:root:    * cm run script "detect os"
INFO:root:           ! cd /work1/zixian/ziw081/CM/repos/local/cache/143bc7ed6d8646af
INFO:root:           ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:           ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:    * cm run script "get generic-sys-util _install _psmisc"
INFO:root:      * cm run script "detect os"
INFO:root:             ! cd /work1/zixian/ziw081/CM/repos/local/cache/8ca7494e1dce4d06
INFO:root:             ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:             ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:           ! cd /work1/zixian/ziw081/CM/repos/local/cache/8ca7494e1dce4d06
INFO:root:           ! call /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/get-generic-sys-util/install.sh from tmp-run.sh
 dnf install -y psmisc


Error: This command has to be run with superuser privileges (under the root user on most systems).
Command failed with status 0

CM error: Portable CM script failed (name = get-generic-sys-util, return code = 256)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note that it is often a portability issue of a third-party tool or a native script
wrapped and unified by this CM script (automation recipe). Please re-run
this script with --repro flag and report this issue with the original
command line, cm-repro directory and full log here:

https://github.com/mlcommons/cm4mlops/issues

The CM concept is to collaboratively fix such issues inside portable CM scripts
to make existing tools and native scripts more portable, interoperable
and deterministic. Thank you!

```

**Comment by arjunsuresh** [comment]
That's bad. Can you please append  `--env.CM_GET_PLATFORM_DETAILS=no` to the run command?

**Comment by zixianwang2022** [comment]
We are getting another issue now. 


```
INFO:root:Python version: 3.10.14
INFO:root:  * cm run script "get compiler"
INFO:root:       ! load /work1/zixian/ziw081/CM/repos/local/cache/3ea44324d2cf4a42/cm-cached-state.json
INFO:root:  * cm run script "get generic-python-lib _package.dmiparser"
INFO:root:       ! load /work1/zixian/ziw081/CM/repos/local/cache/fded4801de8b4bbe/cm-cached-state.json
INFO:root:  * cm run script "get cache dir _name.mlperf-inference-sut-descriptions"
INFO:root:       ! load /work1/zixian/ziw081/CM/repos/local/cache/90c74a04e60b4c0d/cm-cached-state.json
Generating SUT description file for t004_005.hpcfund-pytorch-2.6.0.dev20241108
INFO:root:       ! call "postprocess" from /work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/get-mlperf-inference-sut-description/customize.py


SUT: t004_005.hpcfund-reference-rocm-pytorch-v2.6.0.dev20241108-scc24-base, model: stable-diffusion-xl, scenario: Offline, target_qps updated as 0.506135
New config stored in /work1/zixian/ziw081/CM/repos/local/cache/24fa54383b434e62/t004_005.hpcfund/reference-implementation/rocm-device/pytorch-framework/framework-version-v2.6.0.dev20241108/scc24-base-config.yaml
Traceback (most recent call last):
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_1/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_1/lib/python3.10/site-packages/cmind/cli.py", line 37, in run
    r = cm.access(argv, out='con')
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_1/lib/python3.10/site-packages/cmind/core.py", line 609, in access
    r = action_addr(i)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 211, in run
    r = self._run(i)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 1485, in _run
    r = customize_code.preprocess(ii)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/run-mlperf-inference-app/customize.py", line 246, in preprocess
    r = cm.access(ii)
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_1/lib/python3.10/site-packages/cmind/core.py", line 1297, in access
    return cm.access(i)
  File "/work1/zixian/ziw081/miniconda3/envs/mlperf_1/lib/python3.10/site-packages/cmind/core.py", line 609, in access
    r = action_addr(i)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 211, in run
    r = self._run(i)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 1560, in _run
    r = prepare_and_run_script_with_postprocessing(run_script_input)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 4846, in prepare_and_run_script_with_postprocessing
    rr = run_postprocess(customize_code, customize_common_input, recursion_spaces, env, state, const,
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/automation/script/module.py", line 4896, in run_postprocess
    r = customize_code.postprocess(ii)
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/app-mlperf-inference/customize.py", line 245, in postprocess
    result, valid, power_result = mlperf_utils.get_result_from_log(env['CM_MLPERF_LAST_RELEASE'], model, scenario, output_dir, mode, env.get('CM_MLPERF_INFERENCE_SOURCE_VERSION'))
  File "/work1/zixian/ziw081/CM/repos/mlcommons@cm4mlops/script/get-mlperf-inference-utils/mlperf_utils.py", line 28, in get_result_from_log
    result_ = checker.get_performance_metric(config, mlperf_model, result_path, scenario)
TypeError: get_performance_metric() missing 2 required positional arguments: 'division' and 'system_json'
```


When running the following 
```
# Official Implementation 
cm run script --tags=run-mlperf,inference,_r4.1-dev,_short,_scc24-base \
   --model=sdxl \
   --implementation=reference \
   --framework=pytorch \
   --category=datacenter \
   --scenario=Offline \
   --execution_mode=test \
   --device=rocm \
   --quiet --precision=float16    --env.CM_GET_PLATFORM_DETAILS=no
```

**Comment by anandhu-eng** [comment]
Hi @arjunsuresh , what if we handle it in python itself? 

> @anandhu-eng I have added "-1" in `detect-sudo`. Please check it.

Hi @arjunsuresh , we might have to handle for non interactive environments also.

**Comment by arjunsuresh** [comment]
@zixianwang2022 Are you using the latest inference-src code? If not you might need to do
```
cm rm cache --tags=inference,src -f
```

There were updates in the inference-src repository a couple of weeks back.

**Comment by arjunsuresh** [comment]
Hope this issue is resolved. Feel free to reopen if required.
