### ISSUE TITLE
TypeError: Repos.pull() got an unexpected keyword argument 'extra_cmd_git'

### ISSUE THREAD

**Issue by zixianwang2022** [mlcommons/cm4mlops#521]
Hi, 

I am trying to run `cm pull repo`, but receive the following errors that I have no clues where it comes from. 

```
(mlperf_mgx) [ziw081@aqua mlcommons@cm4mlops]$ cm rm cache --tags=inference,src -f
Deleting CM artifact in /liqid/CM/repos/local/cache/93dcac2ecf22487f with tags "get,mlcommons,inference,src,source,inference-src,inference-source,mlperf,script-artifact-4b57186581024797,version-master-git-dffd29273e98ffcbbfad0e66648c5d390d814509" ...
    Deleted!
Deleting CM artifact in /liqid/CM/repos/local/cache/1cb1e66f4cc94c16 with tags "get,git,repo,repository,clone,_branch.master,_repo.https://github.com/mlcommons/inference,inference,src,script-artifact-ed603e7292974f10" ...
    Deleted!
(mlperf_mgx) [ziw081@aqua mlcommons@cm4mlops]$ cm rm cache --tags=inference -f
Deleting CM artifact in /liqid/CM/repos/local/cache/02212455fe044c47 with tags "get,cache,dir,directory,_name.mlperf-inference-sut-descriptions,mlperf,inference,sut,descriptions,script-artifact-48f4622e059b45ce" ...
    Deleted!
Deleting CM artifact in /liqid/CM/repos/local/cache/41b3714231af419f with tags "get,mlperf,inference,results,dir,local,directory,_version.r4_1-dev,script-artifact-84f3c5aad5e1444b" ...
    Deleted!
Deleting CM artifact in /liqid/CM/repos/local/cache/6ba2e36c51b044f9 with tags "get,mlperf,inference,nvidia,scratch,space,script-artifact-0b2bec8b29fb4ab7" ...
    Deleted!
(mlperf_mgx) [ziw081@aqua mlcommons@cm4mlops]$ cm rm cache --tags=python -f
Deleting CM artifact in /liqid/CM/repos/local/cache/fa1917df358b4b05 with tags "get,python3,python,get-python,get-python3,script-artifact-d0b5dd74373f4a62,version-3.10.15,non-virtual" ...
    Deleted!
(mlperf_mgx) [ziw081@aqua mlcommons@cm4mlops]$ cm pull repo
=======================================================
Alias:    mlcommons@cm4mlops

Traceback (most recent call last):
  File "/liqid/miniconda3/envs/mlperf_mgx/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/liqid/miniconda3/envs/mlperf_mgx/lib/python3.10/site-packages/cmind/cli.py", line 37, in run
    r = cm.access(argv, out='con')
  File "/liqid/miniconda3/envs/mlperf_mgx/lib/python3.10/site-packages/cmind/core.py", line 605, in access
    r = action_addr(i)
  File "/liqid/miniconda3/envs/mlperf_1/lib/python3.11/site-packages/cmind/repo/automation/repo/module.py", line 180, in pull
    r = repos.pull(alias = alias,
TypeError: Repos.pull() got an unexpected keyword argument 'extra_cmd_git'
```

**Comment by zixianwang2022** [comment]
Nevermind. I uninstall and reinstalld `cmind`, it is now functioning properly.
