### ISSUE TITLE
CM Error: TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by johnammon75** [mlcommons/cm4mlops#528]
Howdy! I am running MLPerf using CM and am running into an error `CM error: Portable CM script failed (name = benchmark-program, return code = 256)`. I am running this on Python version 3.11.3.

Do you have any clues or ideas as to what the problem is?

Here is the command I ran:
```
cm run script --tags=run-mlperf,inference,_find-performance,_r4.1-dev,_short,_scc24-base    --model=sdxl    --implementation=reference    --framework=pytorch    --category=datacenter    --scenario=Offline    --execution_mode=test    --device=rocm     --quiet     --precision=float16`
Here is the error output:
`INFO:root:  * cm run script "benchmark-program program"
INFO:root:    * cm run script "detect cpu"
INFO:root:      * cm run script "detect os"
INFO:root:             ! cd /home/johnammon75/CM/repos/local/cache/eb451cfc1e234db9
INFO:root:             ! call /home/johnammon75/CM/repos/mlcommons@cm4mlops/script/detect-os/run.sh from tmp-run.sh
INFO:root:             ! call "postprocess" from /home/johnammon75/CM/repos/mlcommons@cm4mlops/script/detect-os/customize.py
INFO:root:           ! cd /home/johnammon75/CM/repos/local/cache/eb451cfc1e234db9
INFO:root:           ! call /home/johnammon75/CM/repos/mlcommons@cm4mlops/script/detect-cpu/run.sh from tmp-run.sh
INFO:root:           ! call "postprocess" from /home/johnammon75/CM/repos/mlcommons@cm4mlops/script/detect-cpu/customize.py
***************************************************************************
CM script::benchmark-program/run.sh

Run Directory: /home/johnammon75/CM/repos/local/cache/870d30b513714076/inference/text_to_image

CMD: /home/johnammon75/cm/bin/python3 main.py  --scenario Offline --profile stable-diffusion-xl-pytorch  --dataset coco-1024 --dataset-path /home/johnammon75/CM/repos/local/cache/e6b78d27c6ec4a7b/install --dtype fp16 --device cuda   --threads 1 --user_conf '/home/johnammon75/CM/repos/mlcommons@cm4mlops/script/generate-mlperf-inference-user-conf/tmp/3996a959284c4588a9000585bf3e957f.conf' --output /home/johnammon75/CM/repos/local/cache/8230dd65490f4abf/test_results/gigem1-reference-rocm-pytorch-v2.6.0.dev20241111-scc24-base/stable-diffusion-xl/offline/performance/run_1 --model-path /home/johnammon75/CM/repos/local/cache/976d5ca3cedc4bdd/stable_diffusion_fp16 --max-batchsize 1 --ids-path /home/johnammon75/CM/repos/local/cache/e6b78d27c6ec4a7b/install/sample_ids.txt 2>&1 ; echo \$? > exitstatus | tee '/home/johnammon75/CM/repos/local/cache/8230dd65490f4abf/test_results/gigem1-reference-rocm-pytorch-v2.6.0.dev20241111-scc24-base/stable-diffusion-xl/offline/performance/run_1/console.out'

INFO:root:         ! cd /home/johnammon75/CM/repos/local/cache/eb451cfc1e234db9
INFO:root:         ! call /home/johnammon75/CM/repos/mlcommons@cm4mlops/script/benchmark-program/run.sh from tmp-run.sh

/home/johnammon75/cm/bin/python3 main.py  --scenario Offline --profile stable-diffusion-xl-pytorch  --dataset coco-1024 --dataset-path /home/johnammon75/CM/repos/local/cache/e6b78d27c6ec4a7b/install --dtype fp16 --device cuda   --threads 1 --user_conf '/home/johnammon75/CM/repos/mlcommons@cm4mlops/script/generate-mlperf-inference-user-conf/tmp/3996a959284c4588a9000585bf3e957f.conf' --output /home/johnammon75/CM/repos/local/cache/8230dd65490f4abf/test_results/gigem1-reference-rocm-pytorch-v2.6.0.dev20241111-scc24-base/stable-diffusion-xl/offline/performance/run_1 --model-path /home/johnammon75/CM/repos/local/cache/976d5ca3cedc4bdd/stable_diffusion_fp16 --max-batchsize 1 --ids-path /home/johnammon75/CM/repos/local/cache/e6b78d27c6ec4a7b/install/sample_ids.txt 2>&1 ; echo $? > exitstatus | tee '/home/johnammon75/CM/repos/local/cache/8230dd65490f4abf/test_results/gigem1-reference-rocm-pytorch-v2.6.0.dev20241111-scc24-base/stable-diffusion-xl/offline/performance/run_1/console.out'
Traceback (most recent call last):
  File "/home/johnammon75/CM/repos/local/cache/870d30b513714076/inference/text_to_image/main.py", line 25, in <module>
    import coco
  File "/home/johnammon75/CM/repos/local/cache/870d30b513714076/inference/text_to_image/coco.py", line 19, in <module>
    from tools.fid.fid_score import compute_fid
  File "/home/johnammon75/CM/repos/local/cache/870d30b513714076/inference/text_to_image/tools/fid/fid_score.py", line 47, in <module>
    sys.path.insert("..", 0)
TypeError: 'str' object cannot be interpreted as an integer

CM error: Portable CM script failed (name = benchmark-program, return code = 256)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by arjunsuresh** [comment]
Hi @johnammon75 this is expected if you are running the default code now. Please use
"--adr.mlperf-implementation.tags=_branch.dev  - - adr.mlperf-implementation.version=custom"

Only tomorrow we can fix the master version during the inference WG meeting.

**Comment by ChloeCrozier** [comment]
I was having the same issue. I could temporarily fix it when I went into `/root/CM/repos/local/cache/69252d080a244bfc/inference/text_to_image/tools/fid/fid_score.py`.

I changed line 47 to this (swapping ".." and 0):
<img width="489" alt="image" src="https://github.com/user-attachments/assets/39533b2b-8a84-4272-b88c-673f9820f43e">

After that, I re-ran the command my script errored out on, which happened to be:
- `./tmp-run.sh /home/cmuser/venv/cm/bin/python3 main.py --scenario Offline --profile stable-diffusion-xl-pytorch --dataset coco-1024 --dataset-path /root/CM/repos/local/cache/3ae5be25ec254df3/install --dtype fp16 --device cuda --threads 1 --user_conf '/root/CM/repos/mlcommons@cm4mlops/script/generate-mlperf-inference-user-conf/tmp/ca119aba028240afa7f69ee72724bae9.conf' --output /cm-mount/share/competition/mlperf/test_results/9e528a0503c6-reference-gpu-pytorch-v2.5.1-scc24-base_cu124/stable-diffusion-xl/offline/performance/run_1 --model-path /root/CM/repos/local/cache/a17af1c021c14272/stable_diffusion_fp16 --max-batchsize 1 --ids-path /root/CM/repos/local/cache/3ae5be25ec254df3/install/sample_ids.txt`

**Comment by arjunsuresh** [comment]
Closing this issue now as the "inference" repository is now updated with the code fix. Please reopen if there are any issues.
